version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bookstore_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    networks:
      - laravel_network
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: bookstore_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel_network
    depends_on:
      - app

  db:
    image: postgres:15
    container_name: bookstore_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: bookstore_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge

volumes:
  pgdata:
